#!/usr/bin/env node
const { execSync } = require("child_process");
const { join } = require("path")

const lintStaged = join( process.cwd(), `node_modules/.bin/lint-staged`)
const lintStagedRc = join( process.cwd(), `node_modules/@operational/scripts/assets/.lintstagedrc`)

try {
  return execSync(`${lintStaged} -c ${lintStagedRc}`, {
    stdio: "inherit",
  });
} catch (e) {
  process.exit(1);
}
